### ISSUE TITLE
Tray Application

### ISSUE THREAD

**Issue by NTrue** [NTrue/Square9.SecurityDisplay#4]
Should set the app to run as a tray application.

**Comment by NTrue** [comment]
Changeset:
2c90a21ec428

Files:
Square9.SecurityDisplay/Program.cs
Square9.SecurityDisplay/Square9.SecurityDisplay.csproj

Now launches and exits as a tray app.

**Comment by propagated** [comment]
just curious, why should it run as a tray application, and not say a service?

**Comment by NTrue** [comment]
I feel like this application has a very specific use and does not need to be running all the time. I feel like a user would just run it, do what they need to do, and then close it when they are done.
